### PR TITLE
Serious Questions about 2nd paragraph

### PR DESCRIPTION
**Pull request by Identitywoman**
In the either pad edition I did a bunch of editing and in earlier versions and took out the 2nd paragraph and added some other context (the other context is still in the above version but the 2nd paragraph got added back in. I don't think it makes rhetorical logical sense.  I don't think the statements about democracy - networks and power are proven by research (At least none that I have heard of). Networks by their nature lead to hyperconnected nodes HAVEING a lot of power. Look at all the work done about small scale networks and power laws and understanding what happened to the internet - where we are today is ALL power law networks and the power imbalances that creates - these type of thigns WILL happen in whatever new network thing we think we are creating. It is a falicy to think otherwise. This is why I pulled ALL this text from the version I was working on yesterday - it is based on a bunch of assumptions that are NOT realistic. They are techno-utopian mumbo jumob.  I also think pointing to what seems like an assumption of american democracy that is has in effect been bought by special interests - those with money.

### CODE REVIEW

**Comment by jimscarver** [comment]
I think the idea that is being expressed is that decentralization counteracts the power law advantage in the sense that one group cannot not dominate any other webs of trust.  80% in one group has no effect on another trust network.  For example centralized ratings such as those on ebay make it easy to discredit an individual globally by anyone stuffing in bad ratings.  Decentralizing the process in webs of trust make it quite difficult for one group to dominate the system.  Untrustworthy distributed trust networks are discoverable creating incentives to be trustworthy.

I agree the wording was not quite right but I believe there is a point there about decentralization that should be made.

**Comment by du5t** [comment]
Yeah, I think that these statements are about whether or not the infrastructure leans toward accumulation of power. For example, (SSL certification + the browser auditing process) is a market which can be cornered into an oligopoly; value (both in terms of money and credibility) can be accumulated in these highly hierarchical structures and then rents are collected, protected by high barriers of entry. The CA business is incentivized to produce these 'trust cartels', and indeed, one would expect a well-funded, established business to have more incentives to secure their root certs than small or young outfits (until they become 'too big to fail').

It's very difficult to imagine PGP being subjected to the same--its network is a social one, and a dim view is taken of its trust transitivity, oneat least so far. In Bitcoin's case, the network is explicitly less trustworthy if mining power accumulates, and thus, its value should decrease. These latter two are not 'power-law networks', to the best of my knowledge.

This doesn't mean that corruption, malfeasance, or inequity can't be constructed out of the pieces a well-designed decentralized system offers. It just means that they're manifestly poor ingredients for the task.

That being the case, can we make such a nuanced argument in this paper? It's my understanding that the white paper should have a bullish tone--after all, it's discussing the opportunities, not the pitfalls.

**Comment by jimscarver** [comment]
I find is interesting how some positive aspects of the power law are presented in this talk on [institutions verses collaboration](https://www.youtube.com/watch?v=sPQViNNOAkw).

Another factor effecting the balance is like the long tail of the internet and how in the accumulation of trust the corroborators become more and more numerous and diverse across webs of trust.

**Comment by du5t** [comment]
This paragraph went through some major changes during editing, and is now multiple paragraphs with slightly more limited claims. Take a look and see what you think.

**Pull request closed without merging**
